import { Inter } from "next/font/google";
import "./globals.css";
import { SearchProvider } from "../context/SearchContext"; // Importa o SearchProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearchProvider> {/* Envolve os filhos com o SearchProvider */}
          {children}
        </SearchProvider>
      </body>
    </html>
  );
}
